# Generated by Django 3.2.13 on 2022-05-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='别名')),
            ],
            options={
                'verbose_name': '别名库',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('ch_name', models.CharField(blank=True, max_length=200, verbose_name='中文疾病名')),
                ('en_name', models.CharField(blank=True, max_length=200, verbose_name='英文疾病名')),
                ('omim_id', models.CharField(blank=True, max_length=200, verbose_name='OMIM编号')),
                ('orphanet_id', models.CharField(blank=True, max_length=200, verbose_name='Orphanet编号')),
                ('inher_mode', models.CharField(blank=True, max_length=200, verbose_name='遗传模式')),
                ('ch_alias', models.ManyToManyField(blank=True, related_name='dis_alias_ch', to='cancer_database.Alias', verbose_name='中文别名')),
                ('en_alias', models.ManyToManyField(blank=True, related_name='dis_alias_en', to='cancer_database.Alias', verbose_name='英文别名')),
            ],
            options={
                'verbose_name': '疾病库',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=200, upload_to='files', verbose_name='文件上传')),
                ('file_descr', models.TextField(blank=True, verbose_name='文件说明')),
            ],
        ),
        migrations.CreateModel(
            name='Mutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=200, verbose_name='变异类型')),
                ('mut_name', models.CharField(blank=True, max_length=200, verbose_name='变异名称')),
                ('chr_hg19', models.CharField(blank=True, max_length=50, verbose_name='【hg19】染色体')),
                ('pos1_hg19', models.IntegerField(blank=True, null=True, verbose_name='【HG19】位置1')),
                ('pos2_hg19', models.IntegerField(blank=True, null=True, verbose_name='【HG19】位置2')),
                ('ref_hg19', models.CharField(blank=True, max_length=200, verbose_name='【HG19】ref碱基')),
                ('alt_hg19', models.CharField(blank=True, max_length=200, verbose_name='【HG19】alt碱基')),
                ('chr_hg38', models.CharField(blank=True, max_length=50, verbose_name='【hg38】染色体')),
                ('pos1_hg38', models.IntegerField(blank=True, null=True, verbose_name='【HG38】位置1')),
                ('pos2_hg38', models.IntegerField(blank=True, null=True, verbose_name='【H38】位置2')),
                ('ref_hg38', models.CharField(blank=True, max_length=200, verbose_name='【HG38】ref碱基')),
                ('alt_hg38', models.CharField(blank=True, max_length=200, verbose_name='【HG38】alt碱基')),
                ('gene', models.CharField(blank=True, max_length=200, verbose_name='基因')),
                ('nm_id', models.CharField(blank=True, max_length=200, verbose_name='标准转录本（NM）')),
                ('c_point', models.CharField(blank=True, max_length=200, verbose_name='核苷酸变异')),
                ('p_point', models.CharField(blank=True, max_length=200, verbose_name='氨基酸变化')),
            ],
            options={
                'verbose_name': '变异库',
            },
        ),
        migrations.CreateModel(
            name='Guidline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid_type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('guid_name', models.CharField(blank=True, max_length=500, verbose_name='指南名称')),
                ('guid_url', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('guid_abstract', models.TextField(blank=True, verbose_name='指南描述')),
                ('guid_file', models.ManyToManyField(blank=True, related_name='guidline2file', to='cancer_database.File', verbose_name='资料')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_type', models.CharField(blank=True, choices=[('pubmed', 'PubMed'), ('other', '其他')], max_length=50, verbose_name='类型')),
                ('ev_id', models.CharField(blank=True, max_length=50, verbose_name='编号')),
                ('ev_url', models.CharField(blank=True, max_length=500, verbose_name='链接')),
                ('ev_abstract', models.TextField(blank=True, verbose_name='描述')),
                ('ev_file', models.ManyToManyField(blank=True, related_name='ev2file', to='cancer_database.File', verbose_name='资料')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, verbose_name='类型')),
                ('ch_name', models.CharField(blank=True, max_length=200, verbose_name='中文药物名')),
                ('en_name', models.CharField(blank=True, max_length=200, verbose_name='英文药物名')),
                ('drugbank_id', models.CharField(blank=True, max_length=200, verbose_name='drugbank编号')),
                ('ch_alias', models.ManyToManyField(blank=True, related_name='drug_alias_ch', to='cancer_database.Alias', verbose_name='中文别名')),
                ('en_alias', models.ManyToManyField(blank=True, related_name='drug_alias_en', to='cancer_database.Alias', verbose_name='英文别名')),
            ],
            options={
                'verbose_name': '药物库',
            },
        ),
        migrations.CreateModel(
            name='Disease2drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FDA_approve', models.CharField(blank=True, max_length=200, verbose_name='FDA批准状态')),
                ('NMPA_approve', models.CharField(blank=True, max_length=200, verbose_name='NMPA批准状态')),
                ('test_required', models.CharField(blank=True, max_length=200, verbose_name='是否要求基因检测')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_relate_disease', to='cancer_database.disease', verbose_name='相关疾病')),
                ('drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='disease_relate_drug', to='cancer_database.drug', verbose_name='相关药物')),
            ],
            options={
                'verbose_name': '药物库',
            },
        ),
    ]
