# Generated by Django 3.2.13 on 2022-05-12 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disease2drug',
            options={'verbose_name': '疾病药物关系'},
        ),
    ]
