# Generated by Django 3.2.13 on 2022-05-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0002_alter_disease2drug_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV')], max_length=200, verbose_name='变异类型'),
        ),
    ]
