# Generated by Django 3.2.13 on 2022-05-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0003_alter_mutation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': '证据资料'},
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='ev_id',
        ),
        migrations.AddField(
            model_name='evidence',
            name='ev_name',
            field=models.CharField(blank=True, max_length=500, verbose_name='名称'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='pubMed编号'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(blank=True, choices=[('cancer', '癌症'), ('other', '其他')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('molecular', '分子靶向药'), ('chemo', '分子靶向药'), ('other', '其他')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_abstract',
            field=models.TextField(blank=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, verbose_name='变异类型'),
        ),
        migrations.DeleteModel(
            name='Guidline',
        ),
    ]
