# Generated by Django 3.2.13 on 2022-05-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0004_auto_20220513_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='descr',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='drug',
            name='descr',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('molecular', '分子靶向药'), ('chemo', '化疗药'), ('other', '其他')], max_length=50, verbose_name='类型'),
        ),
    ]
