# Generated by Django 3.2.13 on 2022-05-13 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0005_auto_20220513_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='c_point',
            field=models.CharField(blank=True, max_length=200, verbose_name='核苷酸变异(c.)'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='nm_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='标准转录本（NM_id）'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='p_point',
            field=models.CharField(blank=True, max_length=200, verbose_name='氨基酸变化(p.)'),
        ),
    ]
