# Generated by Django 3.2.13 on 2022-05-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0006_auto_20220513_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, verbose_name='变异类型'),
        ),
    ]
