# Generated by Django 3.2.13 on 2022-05-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0007_alter_mutation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='related_drugs',
            field=models.ManyToManyField(blank=True, related_name='drugs_in_drug', to='cancer_database.Drug', verbose_name='包含药物'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='FDA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未知')], max_length=200, verbose_name='FDA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='NMPA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未知')], max_length=200, verbose_name='NMPA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='test_required',
            field=models.CharField(blank=True, choices=[('yes', '用药前要求基因检测'), ('no', '不必须基因检测'), ('na', '未知')], max_length=200, verbose_name='是否要求基因检测'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('drug_group', '药物类'), ('combine', '联合用药'), ('molecular', '分子靶向药'), ('chemo', '化疗药'), ('other', '其他')], max_length=50, verbose_name='类型'),
        ),
    ]
