# Generated by Django 3.2.13 on 2022-05-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0008_auto_20220516_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug2Mut_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(blank=True, max_length=500, verbose_name='名称')),
                ('support_ev_level', models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('default', '默认（同证据类型）'), ('na', '未设置')], max_length=50, verbose_name='最高证据等级')),
                ('drug_impact', models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低'), ('prog_better', '预后好'), ('prog_worse', '预后差'), ('diagnosis', '诊断'), ('no_effect', '无影响'), ('na', '未设置')], max_length=50, verbose_name='用药影响')),
                ('descr', models.TextField(blank=True, verbose_name='临床意义描述')),
            ],
            options={
                'verbose_name': '临床意义小结',
            },
        ),
        migrations.CreateModel(
            name='Mut2drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mut_level', models.CharField(blank=True, choices=[('1', 'I级'), ('2', 'II级'), ('3', 'III级'), ('4', 'IV级'), ('na', '未设置')], max_length=50, verbose_name='治疗分级')),
                ('test_required', models.CharField(blank=True, choices=[('yes', '用药前要求基因检测'), ('no', '不必须基因检测'), ('na', '未定义')], max_length=200, verbose_name='用药前是否要求该基因检测')),
            ],
            options={
                'verbose_name': '药物变异关系',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件管理'},
        ),
        migrations.AddField(
            model_name='disease',
            name='do_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='DOID编号'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='nct_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='NCT编号'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='pub_version',
            field=models.CharField(blank=True, max_length=200, verbose_name='版本/发表日期'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='protein_effect',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, verbose_name='变异类型'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='FDA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未定义')], max_length=200, verbose_name='FDA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='NMPA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未定义')], max_length=200, verbose_name='NMPA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='test_required',
            field=models.CharField(blank=True, choices=[('yes', '用药前要求基因检测'), ('no', '不必须基因检测'), ('na', '未定义')], max_length=200, verbose_name='是否要求基因检测'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_type',
            field=models.CharField(blank=True, choices=[('101_NCCN', 'A级_NCCN临床指南'), ('102_CSCO', 'A级_CSCO临床指南'), ('103_NMPA', 'A级_NMPA批准'), ('104_FDA', 'A级_FDA批准'), ('105_otherGuidline', 'A级_其他指南'), ('201_consensus', 'B级_专家共识'), ('301_CTPhase3', 'B级_III期临床'), ('302_CTBig', 'B级_其他大规模临床'), ('401_CTPhase2', 'B/C级_II期临床'), ('501_CTPhase1', 'B/C级_I期临床'), ('502_CTSmall', 'C级_其他小规模临床'), ('601_Preclinical', 'D级_临床前研究'), ('602_Case', 'D级_病例报道'), ('603_Other', 'D级_其他研究'), ('na', '未定义')], default='na', max_length=50, verbose_name='证据类型'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, verbose_name='变异类型'),
        ),
        migrations.CreateModel(
            name='Mut2evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_impact', models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低')], max_length=100, verbose_name='用药影响')),
                ('support_direct', models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低')], max_length=100, verbose_name='证据方向')),
                ('ev_level', models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('default', '默认（同证据类型）'), ('na', '未设置')], default='na', max_length=50, verbose_name='证据等级')),
                ('descr', models.TextField(blank=True, verbose_name='解释说明')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mu2evidence_evidence', to='cancer_database.evidence', verbose_name='相关证据')),
                ('mut2drug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Mut2drug_evidence', to='cancer_database.mut2drug', verbose_name='药物变异')),
            ],
            options={
                'verbose_name': '药物变异相关原始证据',
            },
        ),
        migrations.AddField(
            model_name='mut2drug',
            name='disease2drug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mut2drug_disease2drug', to='cancer_database.disease2drug', verbose_name='相关疾病药物'),
        ),
        migrations.AddField(
            model_name='mut2drug',
            name='dose_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_dose', to='cancer_database.drug2mut_summary', verbose_name='药量影响'),
        ),
        migrations.AddField(
            model_name='mut2drug',
            name='drug_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_impact2summary', to='cancer_database.drug2mut_summary', verbose_name='药效影响'),
        ),
        migrations.AddField(
            model_name='mut2drug',
            name='mut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='mut2drug_mut', to='cancer_database.mutation', verbose_name='相关变异'),
        ),
        migrations.AddField(
            model_name='mut2drug',
            name='toxi_impact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='drug_toxi2summary', to='cancer_database.drug2mut_summary', verbose_name='毒副作用'),
        ),
        migrations.AddField(
            model_name='drug2mut_summary',
            name='evidences',
            field=models.ManyToManyField(blank=True, related_name='ev2summary', to='cancer_database.Mut2evidence', verbose_name='参考证据'),
        ),
    ]
