# Generated by Django 3.2.13 on 2022-05-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0009_auto_20220523_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'verbose_name': '91 别名库'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': '11 疾病库'},
        ),
        migrations.AlterModelOptions(
            name='disease2drug',
            options={'verbose_name': '21 疾病药物关系'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': '12 药物库'},
        ),
        migrations.AlterModelOptions(
            name='drug2mut_summary',
            options={'verbose_name': '22 临床意义小结'},
        ),
        migrations.AlterModelOptions(
            name='evidence',
            options={'verbose_name': '61 证据资料'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '92 文件管理'},
        ),
        migrations.AlterModelOptions(
            name='mut2drug',
            options={'verbose_name': '23 药物变异关系'},
        ),
        migrations.AlterModelOptions(
            name='mut2evidence',
            options={'verbose_name': '41 药物变异相关原始证据'},
        ),
        migrations.AlterModelOptions(
            name='mutation',
            options={'verbose_name': '13 变异库'},
        ),
    ]
