# Generated by Django 3.2.13 on 2022-05-24 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0010_auto_20220524_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug2mut_summary',
            options={'verbose_name': '31 临床意义小结'},
        ),
        migrations.AlterModelOptions(
            name='mut2drug',
            options={'verbose_name': '22 药物变异关系'},
        ),
    ]
