# Generated by Django 3.2.13 on 2022-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0011_auto_20220524_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='cnv_gene',
            field=models.CharField(blank=True, max_length=200, verbose_name='基因扩增'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fusion_gene1',
            field=models.CharField(blank=True, max_length=200, verbose_name='融合基因1'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fusion_gene2',
            field=models.CharField(blank=True, max_length=200, verbose_name='融合基因2'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fusion_region1',
            field=models.CharField(blank=True, max_length=200, verbose_name='区域1'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='fusion_region2',
            field=models.CharField(blank=True, max_length=200, verbose_name='区域2'),
        ),
    ]
