# Generated by Django 3.2.13 on 2022-05-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0013_auto_20220526_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='disease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='father_disease', to='cancer_database.disease', verbose_name='所属父疾病'),
        ),
        migrations.AddField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='药物商品名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(blank=True, choices=[('cancer', '癌症'), ('sub_cancer', '癌症亚型'), ('other', '其他')], max_length=50, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='drug_impact',
            field=models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低'), ('prog_better', '预后好'), ('prog_worse', '预后差'), ('diagnosis', '诊断'), ('no_effect', '无影响'), ('na', '未定义')], max_length=50, verbose_name='用药影响'),
        ),
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='support_ev_level',
            field=models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('default', '默认（同证据类型）'), ('na', '未定义')], max_length=50, verbose_name='最高证据等级'),
        ),
        migrations.AlterField(
            model_name='mut2drug',
            name='mut_level',
            field=models.CharField(blank=True, choices=[('1', 'I级'), ('2', 'II级'), ('3', 'III级'), ('4', 'IV级'), ('na', '未定义')], max_length=50, verbose_name='治疗分级'),
        ),
        migrations.AlterField(
            model_name='mut2evidence',
            name='ev_level',
            field=models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('default', '默认（同证据类型）'), ('na', '未定义')], default='na', max_length=50, verbose_name='证据等级'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='chr_hg19',
            field=models.CharField(blank=True, max_length=50, verbose_name='【HG19】染色体'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='chr_hg38',
            field=models.CharField(blank=True, max_length=50, verbose_name='【HG38】染色体'),
        ),
    ]
