# Generated by Django 3.2.13 on 2022-05-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0014_auto_20220527_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='descr',
            field=models.TextField(blank=True, verbose_name='变异位点描述'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='descr',
            field=models.TextField(blank=True, verbose_name='疾病描述'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='descr',
            field=models.TextField(blank=True, verbose_name='药物描述'),
        ),
    ]
