# Generated by Django 3.2.13 on 2022-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0015_auto_20220527_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease2drug',
            name='fda_descr',
            field=models.TextField(blank=True, verbose_name='FDA批文说明'),
        ),
        migrations.AddField(
            model_name='disease2drug',
            name='nmpa_descr',
            field=models.TextField(blank=True, verbose_name='NMPA批文说明'),
        ),
    ]
