# Generated by Django 3.2.13 on 2022-05-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0016_auto_20220527_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='drug_impact',
            field=models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低'), ('prog_better', '预后好'), ('prog_worse', '预后差'), ('diagnosis', '诊断'), ('no_effect', '无影响'), ('na', '未定义')], max_length=50, verbose_name='临床影响'),
        ),
    ]
