# Generated by Django 3.2.13 on 2022-06-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0017_alter_drug2mut_summary_drug_impact'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='bak_descr',
            field=models.TextField(blank=True, verbose_name='备注说明'),
        ),
    ]
