# Generated by Django 3.2.13 on 2022-06-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0018_mutation_bak_descr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='disease',
            new_name='father_dis',
        ),
    ]
