# Generated by Django 3.2.13 on 2022-06-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0019_rename_disease_disease_father_dis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(blank=True, choices=[('cancer', '癌症'), ('sub_cancer', '癌症亚型'), ('other', '其他')], max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('drug_group', '药物类'), ('combine', '联合用药'), ('molecular', '分子靶向药'), ('chemo', '化疗药'), ('other', '其他')], max_length=50, null=True, verbose_name='类型'),
        ),
    ]
