# Generated by Django 3.2.13 on 2022-06-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0020_auto_20220606_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ch_alias',
            field=models.ManyToManyField(blank=True, null=True, related_name='dis_alias_ch', to='cancer_database.Alias', verbose_name='中文别名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='ch_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='中文疾病名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='疾病描述'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='do_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='DOID编号'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='en_alias',
            field=models.ManyToManyField(blank=True, null=True, related_name='dis_alias_en', to='cancer_database.Alias', verbose_name='英文别名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英文疾病名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='inher_mode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='遗传模式'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='omim_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='OMIM编号'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='orphanet_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Orphanet编号'),
        ),
    ]
