# Generated by Django 3.2.13 on 2022-06-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0021_auto_20220606_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ch_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='中文疾病名'),
        ),
    ]
