# Generated by Django 3.2.13 on 2022-06-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0022_alter_disease_ch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='ch_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='中文药物名'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='药物描述'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drugbank_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='drugbank编号'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='en_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='英文药物名'),
        ),
    ]
