# Generated by Django 3.2.13 on 2022-06-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0023_auto_20220607_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='ch_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='中文药物名'),
        ),
    ]
