# Generated by Django 3.2.13 on 2022-06-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0024_alter_drug_ch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mutation',
            name='alt_hg19',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='【HG19】alt碱基'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='alt_hg38',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='【HG38】alt碱基'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='bak_descr',
            field=models.TextField(blank=True, null=True, verbose_name='备注说明'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='c_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='核苷酸变异(c.)'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='chr_hg19',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='【HG19】染色体'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='chr_hg38',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='【HG38】染色体'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='cnv_gene',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='基因扩增'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='变异位点描述'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fusion_gene1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='融合基因1'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fusion_gene2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='融合基因2'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fusion_region1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='区域1'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='fusion_region2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='区域2'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='gene',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='基因'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='mut_function',
            field=models.CharField(blank=True, choices=[('LOF', 'Loss_of_function'), ('LLOF', 'Likely_Loss_of_function'), ('GOF', 'Gain_of_function'), ('LGOF', 'Likely_Gain_of_function'), ('NEU', 'Neutral'), ('LNEU', 'Likely_Neutral'), ('SWITCH', 'Switch_of_function'), ('LSWITCH', 'Likely_Switch_of_function'), ('NO', 'NO_effect'), ('unknown', 'Unknown'), ('na', '未定义')], max_length=200, null=True, verbose_name='变异功能'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='nm_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标准转录本（NM_id）'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='p_point',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='氨基酸变化(p.)'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='protein_effect',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, null=True, verbose_name='变异类型'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='ref_hg19',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='【HG19】ref碱基'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='ref_hg38',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='【HG38】ref碱基'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他')], max_length=200, null=True, verbose_name='变异类型'),
        ),
    ]
