# Generated by Django 3.2.13 on 2022-06-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0025_auto_20220607_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('onco', '原癌基因'), ('anti', '抑癌基因'), ('other', '其他'), ('NA', 'NA')], max_length=200, null=True, verbose_name='基因类型')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='基因名称')),
                ('cancer_descr', models.TextField(blank=True, null=True, verbose_name='肿瘤基因描述')),
                ('bak_descr', models.TextField(blank=True, null=True, verbose_name='备注说明')),
            ],
            options={
                'verbose_name': '10 基因库',
            },
        ),
    ]
