# Generated by Django 3.2.13 on 2022-06-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0026_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='药物商品名'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('drug_group', '药物类'), ('combine', '联合用药'), ('molecular', '小分子药物'), ('mAb', '单克隆抗体'), ('fusion_protein', '融合蛋白'), ('alkylating', '烷基化药物'), ('chemo', '化疗药'), ('other', '其他')], max_length=50, null=True, verbose_name='类型'),
        ),
    ]
