# Generated by Django 3.2.13 on 2022-06-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0027_auto_20220607_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease2drug',
            name='descr',
            field=models.TextField(blank=True, verbose_name='药物说明'),
        ),
    ]
