# Generated by Django 3.2.13 on 2022-06-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0028_disease2drug_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease2drug',
            name='FDA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未定义')], max_length=200, null=True, verbose_name='FDA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='NMPA_approve',
            field=models.CharField(blank=True, choices=[('yes', '批准'), ('no', '未批准'), ('na', '未定义')], max_length=200, null=True, verbose_name='NMPA批准状态'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='药物说明'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='fda_descr',
            field=models.TextField(blank=True, null=True, verbose_name='FDA批文说明'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='nmpa_descr',
            field=models.TextField(blank=True, null=True, verbose_name='NMPA批文说明'),
        ),
        migrations.AlterField(
            model_name='disease2drug',
            name='test_required',
            field=models.CharField(blank=True, choices=[('yes', '用药前要求基因检测'), ('no', '不必须基因检测'), ('na', '未定义')], max_length=200, null=True, verbose_name='是否要求基因检测'),
        ),
    ]
