# Generated by Django 3.2.13 on 2022-06-09 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0029_auto_20220609_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='type',
            field=models.CharField(blank=True, choices=[('cancer', '癌症'), ('sub_cancer', '癌症亚型'), ('other', '其他'), ('na', '未定义')], max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('drug_group', '药物类'), ('combine', '联合用药'), ('molecular', '小分子药物'), ('mAb', '单克隆抗体'), ('fusion_protein', '融合蛋白'), ('alkylating', '烷基化药物'), ('chemo', '化疗药'), ('other', '其他'), ('na', '未定义')], max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='type',
            field=models.CharField(blank=True, choices=[('onco', '原癌基因'), ('anti', '抑癌基因'), ('other', '其他'), ('na', '未定义')], max_length=200, null=True, verbose_name='基因类型'),
        ),
        migrations.AlterField(
            model_name='mut2evidence',
            name='drug_impact',
            field=models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低'), ('na', '未定义')], max_length=100, verbose_name='用药影响'),
        ),
        migrations.AlterField(
            model_name='mut2evidence',
            name='support_direct',
            field=models.CharField(blank=True, choices=[('support', '支持'), ('not_support', '不支持'), ('na', '未定义')], max_length=100, verbose_name='证据方向'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='protein_effect',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他'), ('na', '未定义')], max_length=200, null=True, verbose_name='变异类型'),
        ),
        migrations.AlterField(
            model_name='mutation',
            name='type',
            field=models.CharField(blank=True, choices=[('group', '变异类'), ('combine_mut', '合并变异'), ('SNV', 'SNV'), ('InDel', 'InDel'), ('Fusion', 'Fusion'), ('CNV', 'CNV'), ('other', '其他'), ('na', '未定义')], max_length=200, null=True, verbose_name='变异类型'),
        ),
    ]
