# Generated by Django 3.2.13 on 2022-06-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0030_auto_20220609_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='descr',
            field=models.TextField(blank=True, null=True, verbose_name='临床意义描述'),
        ),
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='drug_impact',
            field=models.CharField(blank=True, choices=[('sensitive', '敏感'), ('resistance', '耐药'), ('decreased_response', '疗效降低'), ('no_response', '用药无效'), ('increase_dose', '增加用量'), ('decrease_dose', '降低用量'), ('increase_toxicity', '毒副作用增强'), ('decrease_toxicity', '毒副作用降低'), ('prog_better', '预后好'), ('prog_worse', '预后差'), ('diagnosis', '诊断'), ('no_effect', '无影响'), ('na', '未定义')], max_length=50, null=True, verbose_name='临床影响'),
        ),
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='support_ev_level',
            field=models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('default', '默认（同证据类型）'), ('na', '未定义')], max_length=50, null=True, verbose_name='最高证据等级'),
        ),
    ]
