# Generated by Django 3.2.13 on 2022-06-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0031_auto_20220610_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ch_alias',
            field=models.ManyToManyField(blank=True, related_name='dis_alias_ch', to='cancer_database.Alias', verbose_name='中文别名'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='en_alias',
            field=models.ManyToManyField(blank=True, related_name='dis_alias_en', to='cancer_database.Alias', verbose_name='英文别名'),
        ),
        migrations.AlterField(
            model_name='mut2drug',
            name='mut_level',
            field=models.CharField(blank=True, choices=[('1', 'I级'), ('2', 'II级'), ('3', 'III级'), ('4', 'IV级'), ('na', '未定义')], max_length=50, null=True, verbose_name='治疗分级'),
        ),
        migrations.AlterField(
            model_name='mut2drug',
            name='test_required',
            field=models.CharField(blank=True, choices=[('yes', '用药前要求基因检测'), ('no', '不必须基因检测'), ('na', '未定义')], max_length=200, null=True, verbose_name='用药前是否要求该基因检测'),
        ),
    ]
