# Generated by Django 3.2.13 on 2022-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0032_auto_20220610_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='ev_abstract',
            field=models.TextField(blank=True, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_file',
            field=models.ManyToManyField(blank=True, related_name='ev2file', to='cancer_database.File', verbose_name='资料文件'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_type',
            field=models.CharField(blank=True, choices=[('101_NCCN', 'A级_NCCN临床指南'), ('102_CSCO', 'A级_CSCO临床指南'), ('103_NMPA', 'A级_NMPA批准'), ('104_FDA', 'A级_FDA批准'), ('105_otherGuidline', 'A级_其他指南'), ('201_consensus', 'B级_专家共识'), ('301_CTPhase3', 'B级_III期临床'), ('302_CTBig', 'B级_其他大规模临床'), ('401_CTPhase2', 'B/C级_II期临床'), ('501_CTPhase1', 'B/C级_I期临床'), ('502_CTSmall', 'C级_其他小规模临床'), ('601_Preclinical', 'D级_临床前研究'), ('602_Case', 'D级_病例报道'), ('603_Other', 'D级_其他研究'), ('na', '未定义')], default='na', max_length=50, null=True, verbose_name='证据类型'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='ev_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='nct_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='NCT编号'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='pub_version',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='版本/发表日期'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='pubmed_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='pubMed编号'),
        ),
    ]
