# Generated by Django 3.2.13 on 2022-07-05 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0033_auto_20220627_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='type',
            field=models.CharField(blank=True, choices=[('drug_group', '药物类'), ('combine', '联合用药'), ('molecular', '小分子药物'), ('mAb', '单克隆抗体'), ('fusion_protein', '融合蛋白'), ('alkylating', '烷基化药物'), ('chemo', '化疗药'), ('靶向治疗药物', '靶向治疗药物'), ('免疫治疗药物', '免疫治疗药物'), ('内分泌治疗药物', '内分泌治疗药物'), ('other', '其他'), ('na', '未定义')], max_length=50, null=True, verbose_name='类型'),
        ),
    ]
