# Generated by Django 3.2.13 on 2022-07-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0034_alter_drug_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='contain_mut',
            field=models.ManyToManyField(blank=True, related_name='contain_muts', to='cancer_database.Mutation', verbose_name='包含突变'),
        ),
        migrations.AddField(
            model_name='mutation',
            name='hotspot_mut',
            field=models.ManyToManyField(blank=True, related_name='hotspot_muts', to='cancer_database.Mutation', verbose_name='热点突变'),
        ),
    ]
