# Generated by Django 3.2.13 on 2022-07-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0035_auto_20220706_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug2mut_summary',
            name='evidences_new',
            field=models.ManyToManyField(blank=True, related_name='ev_new2summary', to='cancer_database.Evidence', verbose_name='参考证据'),
        ),
        migrations.AlterField(
            model_name='drug2mut_summary',
            name='evidences',
            field=models.ManyToManyField(blank=True, related_name='ev2summary', to='cancer_database.Mut2evidence', verbose_name='参考原始证据'),
        ),
    ]
