# Generated by Django 3.2.13 on 2022-07-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0036_auto_20220706_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='type',
            field=models.CharField(blank=True, choices=[('onco', '原癌基因'), ('anti', '抑癌基因'), ('oncoandanti', '原癌&抑癌基因'), ('other', '其他'), ('na', '未定义')], max_length=200, null=True, verbose_name='基因类型'),
        ),
    ]
