# Generated by Django 3.2.13 on 2022-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cancer_database', '0037_alter_gene_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutation',
            name='rs_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='dbSNP编号(rs）'),
        ),
        migrations.AlterField(
            model_name='gene',
            name='type',
            field=models.CharField(blank=True, choices=[('原癌基因', '原癌基因'), ('抑癌基因', '抑癌基因'), ('原癌基因&抑癌基因', '原癌基因&抑癌基因'), ('其他', '其他'), ('未定义', '未定义')], max_length=200, null=True, verbose_name='基因类型'),
        ),
    ]
